[project]
name = "fabric-deploy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fabric>=3.2.2",
    "invoke>=2.2.0",
    "paramiko>=3.4.0",
    "pyyaml>=6.0",
    "tabulate>=0.9.0",
]
